# Reset prefix
set -g prefix C-a

# Set window indexing at one instead of zero
set -g base-index 1

# Horizontal and Vertical split
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# Binds r to reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloaded"

# Switch panes using vim keybindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes using vim keybindings
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
